name: Load Test 

on:
  workflow_dispatch:
    inputs:
      msvc:
        description: 'service to test'
        required: true
        default: 'core'
      choice:
        type: choice
        description: Test Type
        options:
        - load
        - soak
        - spike
        - stress
        - simple
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: misc/loadtesting/${{inputs.choice}}_test.js