name: Load Test New Relic 

on:
  workflow_dispatch:
    inputs:
      msvc:
        description: 'service to test'
        required: true
        default: 'core'
env:
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  NEW_RELIC_ACCOUNT: ${{ secrets.NEW_RELIC_ACCOUNT }}
  NEW_RELIC_APP_NAME: my_k6_test
  STATSD_HOST: localhost
  STATSD_PORT: 8125
  K6_SCRIPT: ./script.js
  
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      
      - name: Send metrics to New Relic
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: |
          docker run   -d \
            -h $(hostname) \
            -e NR_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT }} \
            -e NR_API_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
            -p 8125:8125/udp \
            newrelic/nri-statsd:latest 
            
      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          ls
          pwd
          cd misc/loadtesting/
          ls
          K6_STATSD_ENABLE_TAGS=true k6 run --out statsd simple_test.js

          
      
