name: Load Test 

on:
 push:
    branches: [ "main", [dm][ea][vi]* ]
pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: pwd
